# Generated by Django 6.0.4 on 2026-05-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminschedule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='adminschedule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
