# Generated by Django 6.0.4 on 2026-05-03 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_adminschedule_created_at_adminschedule_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminschedule',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='adminschedule',
            name='updated_at',
        ),
    ]
