# Generated by Django 6.0.4 on 2026-05-05 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='meet_link',
            field=models.URLField(blank=True, help_text='Google Meet or video call link sent to client on confirmation'),
        ),
    ]
